### ISSUE TITLE
Love the extension but sadly it no longer works.

### ISSUE THREAD

**Issue by fluffyjin** [CyrilCommando/SankakuCacher#1] opened 2020-10-25 00:50 UTC
Can I expect any updates or is it a dead project? Thnx

**Comment by CyrilCommando** [comment] 2020-10-25 03:57
I had no idea it was broke, thanks for letting me know. It should be fixed. Let me know if it doesn't work again. As for updates, you can expect one. I've had a version I've been using for a number of months now with the autofav feature working. That functionality will be included in the fixed version I'll upload in a minute. 

Unfortunately, a lot of the functionality I had planned (like the sort by tags, mass delete and etc) is gated behind NaCl and PNaCl executables (at least, if I were to do it in a way I would be satisfied with) in the extension. That goes beyond my experience with javascript, html and css because it would require me to learn C++. I had begun to do that but I'm already familiar in a couple languages and I ultimately didn't feel like starting from scratch in a completely new one.

**Comment by fluffyjin** [comment] 2020-10-25 04:03
Thank you for your work. I wasn't expecting an answer let alone an answer so quickly. I can't wait for your future updates. There's nothing useful out there. This is the best piece of software I personally enjoy using while visiting the site. Thanks again

**Comment by fluffyjin** [comment] 2020-10-25 04:09
This is the error I'm experiencing if it helps. [https://imgur.com/a/51sWb5M](url)

**Comment by CyrilCommando** [comment] 2020-10-25 17:12
Yeah, I was able to reproduce it immediately. https://github.com/CyrilCommando/SankakuCacher/releases/tag/1.3 Here's the latest with autofav, the fix, and a working mp4s/webms option. Apparently installing chrome extensions from outside of the web store is a disaster, so I won't even bother to include a .crx. Just lemme know if anything breaks again.

**Closed as completed** 2021-03-22 15:57 UTC
